apiVersion: v1
kind: Service
metadata:
  name: "jyjg-kotlin-springboot-appa"
  labels:
    app: "jyjg-kotlin-springboot-appa"
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
    - port: 443
      protocol: TCP
      targetPort: 8443
      name: https
  selector:
    app: "jyjg-kotlin-springboot-appa"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "jyjg-kotlin-springboot-appa"
spec:
  selector:
    matchLabels:
      app: "jyjg-kotlin-springboot-appa"
  replicas: 2
  template:
    metadata:
      labels:
        app: "jyjg-kotlin-springboot-appa"
    spec:
      containers:
        - name: "jyjg-kotlin-springboot-appa"
          image: "garyjyao/jyjg-kotlin-springboot-appa:latest"
          ports:
            - containerPort: 8080
            - containerPort: 8443
